services:
  palworld:
    #restart: always
    container_name: palworld-win
    image: palworld-win
    build: .
    env_file:
      - .env
    networks:
      - default
    volumes:
      - ./palworld:/palworld
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8211:8211/udp"
      - "25575:25575/tcp"
      - "8212:8212/tcp"
